version: '3.1'

services:

  db:
    container_name: test_db
    hostname: test_db
    image: mysql
    restart: always
    volumes:
      - mysql-test:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test1224
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'

volumes:
  mysql-test: